# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designs\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 211)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(350, 150, 93, 28))
        self.StartButton.setObjectName("StartButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 55, 16))
        self.label_2.setObjectName("label_2")
        self.LineSeed = QtWidgets.QLineEdit(self.centralwidget)
        self.LineSeed.setGeometry(QtCore.QRect(350, 40, 113, 22))
        self.LineSeed.setMaxLength(5)
        self.LineSeed.setObjectName("LineSeed")
        self.TypeGeneration = QtWidgets.QComboBox(self.centralwidget)
        self.TypeGeneration.setGeometry(QtCore.QRect(350, 70, 111, 22))
        self.TypeGeneration.setObjectName("TypeGeneration")
        self.TypeGeneration.addItem("")
        self.TypeGeneration.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(350, 110, 201, 20))
        self.checkBox.setObjectName("checkBox")
        self.Line = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Line.setGeometry(QtCore.QRect(20, 40, 301, 141))
        self.Line.setObjectName("Line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartButton.setText(_translate("MainWindow", "Старт"))
        self.label.setText(_translate("MainWindow", "Текстовая подсказка"))
        self.label_2.setText(_translate("MainWindow", "Сид"))
        self.TypeGeneration.setItemText(0, _translate("MainWindow", "Изображение"))
        self.TypeGeneration.setItemText(1, _translate("MainWindow", "Анимация"))
        self.checkBox.setText(_translate("MainWindow", "Промежуточные результаты"))
